//! Mistral Vibe adapter — symlinked skills + generated agent TOML configs.
//!
//! Mirrors `cli/adapters/vibe.js`:
//!
//! - **Skills**: `<scope>/.vibe/skills/<id>` directory symlink. Project scope
//!   targets `<project>/.vibe/skills/` (relative link), global targets
//!   `~/.vibe/skills/` (absolute link).
//! - **Agents**: `~/.vibe/agents/<id>.toml` generated TOML config. Global-only
//!   (Vibe has no project-scoped agent location).
//! - **Teams / Guides**: not supported.
//!
//! `detect()` keys on `.vibe/` in the project directory.
//!
//! The generated TOML is a minimal config: agent id, description, and an
//! empty tools array. The Node oracle reads `item.description` and `item.tools`
//! from upstream metadata, but our `Item` does not carry those fields yet —
//! the adapter matches Node's *fallback* path (description = id, tools = []).
//! Parsing the agent frontmatter to populate the TOML can land when `Item`
//! gains a metadata field.

use std::fs;
use std::path::{Path, PathBuf};

use super::base::{
    Action, AuditEntry, ContentType, FrameworkAdapter, InstallCtx, InstallResult, Item, Scope,
    Strategy,
};
use super::symlink::{is_symlink, link_target, remove_link, symlink_dir};
use crate::error::{Error, Result};

pub struct Vibe;

impl Vibe {
    fn home() -> Result<PathBuf> {
        dirs::home_dir().ok_or(Error::Todo("no home dir"))
    }

    fn skills_base(&self, project_dir: &Path, scope: Scope) -> Result<PathBuf> {
        Ok(match scope {
            Scope::Global => Self::home()?.join(".vibe/skills"),
            _ => project_dir.join(".vibe/skills"),
        })
    }

    fn agents_base() -> Result<PathBuf> {
        Ok(Self::home()?.join(".vibe/agents"))
    }

    fn install_skill(&self, item: &Item, ctx: &InstallCtx<'_>) -> Result<InstallResult> {
        let base = self.skills_base(ctx.project_dir, ctx.scope)?;
        let target = base.join(&item.id);
        if ctx.options.dry_run {
            return Ok(InstallResult {
                action: Action::Created,
                path: target,
                details: Some("dry-run".to_string()),
            });
        }
        if target.exists() && !ctx.options.force {
            return Ok(InstallResult {
                action: Action::Skipped,
                path: target,
                details: Some("already exists".to_string()),
            });
        }
        fs::create_dir_all(&base)?;
        if is_symlink(&target) || target.exists() {
            remove_link(&target)?;
        }
        let link = link_target(&item.source_dir, &base, ctx.scope)?;
        symlink_dir(&link, &target)?;
        Ok(InstallResult {
            action: Action::Created,
            path: target,
            details: None,
        })
    }

    fn install_agent(&self, item: &Item, ctx: &InstallCtx<'_>) -> Result<InstallResult> {
        let agents = Self::agents_base()?;
        let target = agents.join(format!("{}.toml", item.id));
        if ctx.options.dry_run {
            return Ok(InstallResult {
                action: Action::Created,
                path: target,
                details: Some("dry-run".to_string()),
            });
        }
        if target.exists() && !ctx.options.force {
            return Ok(InstallResult {
                action: Action::Skipped,
                path: target,
                details: Some("already exists".to_string()),
            });
        }
        fs::create_dir_all(&agents)?;
        let source_md = item.source_dir.join(format!("{}.md", item.id));
        let toml = format!(
            "# Agent: {id}\n\
             # Generated by agent-almanac CLI\n\
             # Source: {source}\n\
             \n\
             [agent]\n\
             name = \"{id}\"\n\
             description = \"{id}\"\n\
             tools = []\n\
             \n\
             [agent.prompt]\n\
             system_prompt_id = \"{id}\"\n",
            id = item.id,
            source = source_md.display(),
        );
        fs::write(&target, toml)?;
        Ok(InstallResult {
            action: Action::Created,
            path: target,
            details: None,
        })
    }
}

impl FrameworkAdapter for Vibe {
    fn id(&self) -> &'static str {
        "vibe"
    }

    fn display_name(&self) -> &'static str {
        "Mistral Vibe"
    }

    fn strategy(&self) -> Strategy {
        Strategy::Symlink
    }

    fn content_types(&self) -> &'static [ContentType] {
        &[ContentType::Skill, ContentType::Agent]
    }

    fn detect(&self, project_dir: &Path) -> Result<bool> {
        Ok(project_dir.join(".vibe").exists())
    }

    fn target_path(&self, project_dir: &Path, scope: Scope) -> Result<PathBuf> {
        Ok(match scope {
            Scope::Global => Self::home()?.join(".vibe"),
            _ => project_dir.join(".vibe"),
        })
    }

    fn install(&self, item: &Item, ctx: &InstallCtx<'_>) -> Result<InstallResult> {
        match item.kind {
            ContentType::Skill => self.install_skill(item, ctx),
            ContentType::Agent => self.install_agent(item, ctx),
            ContentType::Team | ContentType::Guide => Ok(InstallResult {
                action: Action::Skipped,
                path: self.target_path(ctx.project_dir, ctx.scope)?,
                details: Some(format!("vibe does not install {:?}s", item.kind)),
            }),
        }
    }

    fn uninstall(&self, item: &Item, ctx: &InstallCtx<'_>) -> Result<InstallResult> {
        match item.kind {
            ContentType::Skill => {
                let target = self
                    .skills_base(ctx.project_dir, ctx.scope)?
                    .join(&item.id);
                if ctx.options.dry_run {
                    return Ok(InstallResult {
                        action: Action::Removed,
                        path: target,
                        details: Some("dry-run".to_string()),
                    });
                }
                if !target.exists() && !is_symlink(&target) {
                    return Ok(InstallResult {
                        action: Action::Skipped,
                        path: target,
                        details: Some("not installed".to_string()),
                    });
                }
                remove_link(&target)?;
                Ok(InstallResult {
                    action: Action::Removed,
                    path: target,
                    details: None,
                })
            }
            ContentType::Agent => {
                let target = Self::agents_base()?.join(format!("{}.toml", item.id));
                if ctx.options.dry_run {
                    return Ok(InstallResult {
                        action: Action::Removed,
                        path: target,
                        details: Some("dry-run".to_string()),
                    });
                }
                if !target.exists() {
                    return Ok(InstallResult {
                        action: Action::Skipped,
                        path: target,
                        details: Some("not installed".to_string()),
                    });
                }
                fs::remove_file(&target)?;
                Ok(InstallResult {
                    action: Action::Removed,
                    path: target,
                    details: None,
                })
            }
            ContentType::Team | ContentType::Guide => Ok(InstallResult {
                action: Action::Skipped,
                path: self.target_path(ctx.project_dir, ctx.scope)?,
                details: Some(format!("vibe does not install {:?}s", item.kind)),
            }),
        }
    }

    fn list_installed(&self, project_dir: &Path, scope: Scope) -> Result<Vec<Item>> {
        let mut items = Vec::new();
        let skills = self.skills_base(project_dir, scope)?;
        if skills.is_dir() {
            for entry in fs::read_dir(&skills)? {
                let entry = entry?;
                let path = entry.path();
                if is_symlink(&path) {
                    items.push(Item {
                        kind: ContentType::Skill,
                        id: entry.file_name().to_string_lossy().into_owned(),
                        source_dir: fs::read_link(&path).unwrap_or_default(),
                        domain: None,
                    });
                }
            }
        }
        if let Ok(agents) = Self::agents_base() {
            if agents.is_dir() {
                for entry in fs::read_dir(&agents)? {
                    let entry = entry?;
                    let name = entry.file_name();
                    let name = name.to_string_lossy();
                    if let Some(stem) = name.strip_suffix(".toml") {
                        items.push(Item {
                            kind: ContentType::Agent,
                            id: stem.to_string(),
                            source_dir: entry.path(),
                            domain: None,
                        });
                    }
                }
            }
        }
        items.sort_by(|a, b| a.id.cmp(&b.id));
        Ok(items)
    }

    fn audit(&self, project_dir: &Path, scope: Scope) -> Result<AuditEntry> {
        let installed = self.list_installed(project_dir, scope)?;
        let mut entry = AuditEntry {
            framework: self.display_name().to_string(),
            ..Default::default()
        };
        if installed.is_empty() {
            entry.warnings.push("No Vibe content installed".to_string());
        } else {
            entry.ok.push(format!("{} items installed", installed.len()));
        }
        Ok(entry)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adapters::base::InstallOptions;
    use serial_test::serial;

    fn skill_item(id: &str, source_dir: PathBuf) -> Item {
        Item {
            kind: ContentType::Skill,
            id: id.to_string(),
            source_dir,
            domain: Some("general".to_string()),
        }
    }
    fn agent_item(id: &str, source_dir: PathBuf) -> Item {
        Item {
            kind: ContentType::Agent,
            id: id.to_string(),
            source_dir,
            domain: None,
        }
    }

    fn write_skill(skills_root: &Path, id: &str) -> PathBuf {
        let skill_dir = skills_root.join(id);
        fs::create_dir_all(&skill_dir).unwrap();
        fs::write(skill_dir.join("SKILL.md"), "---\nname: demo\n---\n").unwrap();
        skill_dir
    }

    fn write_agent(agents_root: &Path, id: &str) -> PathBuf {
        fs::create_dir_all(agents_root).unwrap();
        fs::write(agents_root.join(format!("{id}.md")), "---\nname: demo\n---\n").unwrap();
        agents_root.to_path_buf()
    }

    #[test]
    fn detect_keys_on_dot_vibe() {
        let dir = tempfile::tempdir().unwrap();
        assert!(!Vibe.detect(dir.path()).unwrap());
        fs::create_dir(dir.path().join(".vibe")).unwrap();
        assert!(Vibe.detect(dir.path()).unwrap());
    }

    #[test]
    fn content_types_skill_and_agent() {
        assert!(Vibe.supports(ContentType::Skill));
        assert!(Vibe.supports(ContentType::Agent));
        assert!(!Vibe.supports(ContentType::Team));
        assert!(!Vibe.supports(ContentType::Guide));
    }

    #[test]
    fn install_skill_project_writes_relative_symlink() {
        let dir = tempfile::tempdir().unwrap();
        let skill_dir = write_skill(&dir.path().join("skills"), "demo");
        let item = skill_item("demo", skill_dir);
        let ctx = InstallCtx {
            project_dir: dir.path(),
            almanac_root: dir.path(),
            scope: Scope::Project,
            options: InstallOptions::default(),
        };
        let result = Vibe.install(&item, &ctx).unwrap();
        assert_eq!(result.action, Action::Created);
        let target = dir.path().join(".vibe/skills/demo");
        assert!(is_symlink(&target));
        assert!(fs::read_link(&target).unwrap().is_relative());
    }

    #[test]
    fn install_skill_skips_when_present_without_force() {
        let dir = tempfile::tempdir().unwrap();
        let skill_dir = write_skill(&dir.path().join("skills"), "demo");
        let item = skill_item("demo", skill_dir);
        let ctx = InstallCtx {
            project_dir: dir.path(),
            almanac_root: dir.path(),
            scope: Scope::Project,
            options: InstallOptions::default(),
        };
        Vibe.install(&item, &ctx).unwrap();
        let result = Vibe.install(&item, &ctx).unwrap();
        assert_eq!(result.action, Action::Skipped);
    }

    #[test]
    #[serial]
    fn install_agent_writes_toml_into_home() {
        let home = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", home.path());
        let almanac = tempfile::tempdir().unwrap();
        write_agent(&almanac.path().join("agents"), "demo-agent");
        let item = agent_item("demo-agent", almanac.path().join("agents"));
        let ctx = InstallCtx {
            project_dir: almanac.path(),
            almanac_root: almanac.path(),
            scope: Scope::Project,
            options: InstallOptions::default(),
        };
        let result = Vibe.install(&item, &ctx).unwrap();
        assert_eq!(result.action, Action::Created);
        let toml = home.path().join(".vibe/agents/demo-agent.toml");
        assert!(toml.is_file());
        let content = fs::read_to_string(&toml).unwrap();
        assert!(content.contains("name = \"demo-agent\""));
        assert!(content.contains("[agent.prompt]"));
        assert!(content.contains("tools = []"));
    }

    #[test]
    fn uninstall_skill_removes_symlink() {
        let dir = tempfile::tempdir().unwrap();
        let skill_dir = write_skill(&dir.path().join("skills"), "demo");
        let item = skill_item("demo", skill_dir);
        let ctx = InstallCtx {
            project_dir: dir.path(),
            almanac_root: dir.path(),
            scope: Scope::Project,
            options: InstallOptions::default(),
        };
        Vibe.install(&item, &ctx).unwrap();
        let result = Vibe.uninstall(&item, &ctx).unwrap();
        assert_eq!(result.action, Action::Removed);
        assert!(!is_symlink(&dir.path().join(".vibe/skills/demo")));
    }

    #[test]
    fn uninstall_skill_idempotent_when_missing() {
        let dir = tempfile::tempdir().unwrap();
        let item = skill_item("demo", dir.path().join("skills/demo"));
        let ctx = InstallCtx {
            project_dir: dir.path(),
            almanac_root: dir.path(),
            scope: Scope::Project,
            options: InstallOptions::default(),
        };
        let result = Vibe.uninstall(&item, &ctx).unwrap();
        assert_eq!(result.action, Action::Skipped);
    }

    #[test]
    #[serial]
    fn uninstall_agent_removes_toml() {
        let home = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", home.path());
        let almanac = tempfile::tempdir().unwrap();
        write_agent(&almanac.path().join("agents"), "demo-agent");
        let item = agent_item("demo-agent", almanac.path().join("agents"));
        let ctx = InstallCtx {
            project_dir: almanac.path(),
            almanac_root: almanac.path(),
            scope: Scope::Project,
            options: InstallOptions::default(),
        };
        Vibe.install(&item, &ctx).unwrap();
        let result = Vibe.uninstall(&item, &ctx).unwrap();
        assert_eq!(result.action, Action::Removed);
        assert!(!home.path().join(".vibe/agents/demo-agent.toml").exists());
    }

    #[test]
    #[serial]
    fn list_and_audit_report_both_kinds() {
        let home = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", home.path());
        let dir = tempfile::tempdir().unwrap();
        let skill_dir = write_skill(&dir.path().join("skills"), "demo-skill");
        write_agent(&dir.path().join("agents"), "demo-agent");

        let ctx = InstallCtx {
            project_dir: dir.path(),
            almanac_root: dir.path(),
            scope: Scope::Project,
            options: InstallOptions::default(),
        };
        Vibe.install(&skill_item("demo-skill", skill_dir), &ctx)
            .unwrap();
        Vibe.install(
            &agent_item("demo-agent", dir.path().join("agents")),
            &ctx,
        )
        .unwrap();

        let listed = Vibe.list_installed(dir.path(), Scope::Project).unwrap();
        let ids: Vec<_> = listed.iter().map(|i| i.id.as_str()).collect();
        assert_eq!(ids, vec!["demo-agent", "demo-skill"]);

        let entry = Vibe.audit(dir.path(), Scope::Project).unwrap();
        assert_eq!(entry.ok, vec!["2 items installed".to_string()]);
    }

    #[test]
    #[serial]
    fn audit_warns_when_empty() {
        let dir = tempfile::tempdir().unwrap();
        // Point HOME at an empty dir too so the agent scan finds nothing.
        let home = tempfile::tempdir().unwrap();
        std::env::set_var("HOME", home.path());
        let entry = Vibe.audit(dir.path(), Scope::Project).unwrap();
        assert_eq!(entry.warnings, vec!["No Vibe content installed".to_string()]);
    }

    #[test]
    fn non_supported_kinds_skip() {
        let dir = tempfile::tempdir().unwrap();
        let ctx = InstallCtx {
            project_dir: dir.path(),
            almanac_root: dir.path(),
            scope: Scope::Project,
            options: InstallOptions::default(),
        };
        let team = Item {
            kind: ContentType::Team,
            id: "demo-team".to_string(),
            source_dir: dir.path().to_path_buf(),
            domain: None,
        };
        let result = Vibe.install(&team, &ctx).unwrap();
        assert_eq!(result.action, Action::Skipped);
    }
}
