/**
 * colors.js - Theme palette system (facade)
 *
 * Data: auto-generated by Rscript generate-palette-colors.R
 * Config: hand-edited in color-config.js
 *
 * This module re-exports everything so existing imports stay unchanged.
 */

import {
  PALETTES, AGENT_PALETTE_COLORS, TEAM_PALETTE_COLORS,
} from './colors-generated.js';

export {
  COMPLEXITY_CONFIG, COMPLEXITY_BADGE_COLORS, FEATURED_NODES,
  AGENT_PRIORITY_CONFIG, TEAM_CONFIG,
} from './color-config.js';

// ── Active theme state ──────────────────────────────────────────────
let currentTheme = 'cyberpunk';

export function getColor(domain) {
  return PALETTES[currentTheme]?.[domain] || '#ffffff';
}

export function setTheme(name) {
  if (PALETTES[name]) {
    currentTheme = name;
  }
}

export function getCurrentPalette() {
  return { ...PALETTES[currentTheme] };
}

export function getThemeNames() {
  return Object.keys(PALETTES);
}

export function getCurrentThemeName() {
  return currentTheme;
}

// ── Agent color lookup ──────────────────────────────────────────────
export function getAgentColor(agentId) {
  if (agentId && AGENT_PALETTE_COLORS[currentTheme]?.[agentId]) {
    return AGENT_PALETTE_COLORS[currentTheme][agentId];
  }
  const colors = AGENT_PALETTE_COLORS[currentTheme];
  if (colors) {
    const vals = Object.values(colors);
    return vals[0] || '#ffd700';
  }
  return '#ffd700';
}

// ── Team color lookup ───────────────────────────────────────────────
export function getTeamColor(teamId) {
  if (teamId && TEAM_PALETTE_COLORS[currentTheme]?.[teamId]) {
    return TEAM_PALETTE_COLORS[currentTheme][teamId];
  }
  const colors = TEAM_PALETTE_COLORS[currentTheme];
  if (colors) {
    const vals = Object.values(colors);
    return vals[0] || '#00ffcc';
  }
  return '#00ffcc';
}

// ── Hex conversion utility ──────────────────────────────────────────
const _rgbaCache = new Map();
export function hexToRgba(hex, alpha) {
  const key = hex + '|' + alpha;
  let val = _rgbaCache.get(key);
  if (val !== undefined) return val;
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  val = `rgba(${r},${g},${b},${alpha})`;
  _rgbaCache.set(key, val);
  return val;
}
