/**
 * color-config.js - Hand-edited viz configuration (not generated)
 *
 * Static layout/rendering constants that are NOT derived from palettes.
 * For palette colors, see colors-generated.js (auto-generated by R).
 */

// ── Complexity node config ──────────────────────────────────────────
export const COMPLEXITY_CONFIG = {
  basic:        { radius: 5, glowRadius: 14, glowOpacity: 0.4,  label: 'Basic' },
  intermediate: { radius: 5, glowRadius: 18, glowOpacity: 0.5,  label: 'Intermediate' },
  advanced:     { radius: 5, glowRadius: 22, glowOpacity: 0.6,  label: 'Advanced' },
};

export const COMPLEXITY_BADGE_COLORS = {
  basic:        '#00ff88',
  intermediate: '#ffdd00',
  advanced:     '#dd44ff',
};

// ── Featured hub nodes (viz-layer config, not skill metadata) ────────
export const FEATURED_NODES = {
  'create-skill':        { radius: 9, tier: 'primary' },
  'evolve-skill':        { radius: 7, tier: 'secondary' },
  'create-skill-glyph':  { radius: 7, tier: 'secondary' },
};

// ── Agent node config ───────────────────────────────────────────────
export const AGENT_PRIORITY_CONFIG = {
  critical: { radius: 8, glowRadius: 24, glowOpacity: 0.7 },
  high:     { radius: 6, glowRadius: 18, glowOpacity: 0.5 },
  normal:   { radius: 5, glowRadius: 14, glowOpacity: 0.4 },
};

// ── Team node config ────────────────────────────────────────────────
export const TEAM_CONFIG = {
  radius: 7,
  glowRadius: 20,
  glowOpacity: 0.55,
};
