/**
 * colors.js - Theme palette system with 9 switchable colormaps
 *
 * Provides: getColor, setTheme, getCurrentPalette, getThemeNames
 * Backward compat: DOMAIN_COLORS Proxy delegates to active palette
 */

// ── Domain order (alphabetical) for consistent palette assignment ──
const DOMAIN_ORDER = [
  '3d-printing',
  'a2a-protocol',
  'alchemy',
  'animal-training',
  'blender',
  'bushcraft',
  'compliance',
  'containerization',
  'crafting',
  'data-serialization',
  'defensive',
  'design',
  'devops',
  'diffusion',
  'esoteric',
  'gardening',
  'general',
  'geometry',
  'git',
  'hildegard',
  'intellectual-property',
  'jigsawr',
  'lapidary',
  'library-science',
  'maintenance',
  'mcp-integration',
  'mlops',
  'morphic',
  'mycology',
  'number-theory',
  'observability',
  'project-management',
  'prospecting',
  'r-packages',
  'relocation',
  'reporting',
  'review',
  'shiny',
  'stochastic-processes',
  'swarm',
  'tcg',
  'theoretical-science',
  'travel',
  'versioning',
  'visualization',
  'web-dev',
  'workflow-visualization',
];

// ── 9 named palettes: one hex color per domain (47 domains) ────────
const PALETTES = {
  cyberpunk: {
    '3d-printing':               '#55aadd',
    'a2a-protocol':              '#44bbaa',
    'alchemy':                   '#ffaa33',
    'animal-training':           '#ff9944',
    'blender':                   '#ee8833',
    'bushcraft':                 '#88cc44',
    'compliance':                '#ff3366',
    'containerization':          '#44ddff',
    'crafting':                  '#cc8855',
    'data-serialization':        '#44aaff',
    'defensive':                 '#ff4444',
    'design':                    '#ff88dd',
    'devops':                    '#00ff88',
    'diffusion':                 '#cc77ff',
    'esoteric':                  '#dd44ff',
    'gardening':                 '#44bb66',
    'general':                   '#ccccff',
    'geometry':                  '#55ccdd',
    'git':                       '#66ffcc',
    'hildegard':                 '#99bb44',
    'intellectual-property':     '#33ccff',
    'jigsawr':                   '#22ddaa',
    'lapidary':                  '#cc8866',
    'library-science':           '#8B7355',
    'maintenance':               '#aabb88',
    'mcp-integration':           '#00ccaa',
    'mlops':                     '#aa66ff',
    'morphic':                   '#bb88ff',
    'mycology':                  '#aa77cc',
    'number-theory':             '#7799ff',
    'observability':             '#ffaa00',
    'project-management':        '#ff8844',
    'prospecting':               '#ddaa33',
    'r-packages':                '#00f0ff',
    'relocation':                '#ff9977',
    'reporting':                 '#ffdd00',
    'review':                    '#ff66aa',
    'shiny':                     '#3399ff',
    'stochastic-processes':      '#77aaff',
    'swarm':                     '#aadd44',
    'tcg':                       '#ff5577',
    'theoretical-science':       '#ddbb55',
    'travel':                    '#66cc99',
    'versioning':                '#88ddaa',
    'visualization':             '#ee77cc',
    'web-dev':                   '#ff6633',
    'workflow-visualization':    '#66dd88',
  },

  viridis: {
    '3d-printing':               '#440154',
    'a2a-protocol':              '#460A5D',
    'alchemy':                   '#471365',
    'animal-training':           '#481B6D',
    'blender':                   '#482274',
    'bushcraft':                 '#472A7A',
    'compliance':                '#46317E',
    'containerization':          '#443883',
    'crafting':                  '#423F85',
    'data-serialization':        '#404688',
    'defensive':                 '#3D4D8A',
    'design':                    '#3A538B',
    'devops':                    '#375A8C',
    'diffusion':                 '#34608D',
    'esoteric':                  '#31668E',
    'gardening':                 '#2F6C8E',
    'general':                   '#2C718E',
    'geometry':                  '#2A778E',
    'git':                       '#287D8E',
    'hildegard':                 '#26828E',
    'intellectual-property':     '#23888E',
    'jigsawr':                   '#218E8D',
    'lapidary':                  '#21908D',
    'library-science':           '#20928C',
    'maintenance':               '#1F988B',
    'mcp-integration':           '#1F9E89',
    'mlops':                     '#20A386',
    'morphic':                   '#23A983',
    'mycology':                  '#28AE80',
    'number-theory':             '#2CB17E',
    'observability':             '#2FB47C',
    'project-management':        '#38B977',
    'prospecting':               '#42BE71',
    'r-packages':                '#4EC36B',
    'relocation':                '#5AC864',
    'reporting':                 '#66CC5D',
    'review':                    '#74D055',
    'shiny':                     '#83D34C',
    'stochastic-processes':      '#91D742',
    'swarm':                     '#A1DA38',
    'tcg':                       '#B1DD2E',
    'theoretical-science':       '#C1DF25',
    'travel':                    '#D0E11C',
    'versioning':                '#D8E21A',
    'visualization':             '#DFE318',
    'web-dev':                   '#EFE51C',
    'workflow-visualization':    '#FDE725',
  },

  magma: {
    '3d-printing':               '#000004',
    'a2a-protocol':              '#02020D',
    'alchemy':                   '#06051A',
    'animal-training':           '#0C0925',
    'blender':                   '#130D33',
    'bushcraft':                 '#1A1041',
    'compliance':                '#21114F',
    'containerization':          '#2B115E',
    'crafting':                  '#35106A',
    'data-serialization':        '#3F0F73',
    'defensive':                 '#491078',
    'design':                    '#52137C',
    'devops':                    '#5C167F',
    'diffusion':                 '#651A80',
    'esoteric':                  '#6E1E81',
    'gardening':                 '#782281',
    'general':                   '#812581',
    'geometry':                  '#8B2981',
    'git':                       '#942C80',
    'hildegard':                 '#9D2F7F',
    'intellectual-property':     '#A7317D',
    'jigsawr':                   '#B1357B',
    'lapidary':                  '#B6377A',
    'library-science':           '#BB3978',
    'maintenance':               '#C43C75',
    'mcp-integration':           '#CE4071',
    'mlops':                     '#D6456C',
    'morphic':                   '#DF4A68',
    'mycology':                  '#E75263',
    'number-theory':             '#EA5661',
    'observability':             '#ED5A5F',
    'project-management':        '#F2645C',
    'prospecting':               '#F66E5C',
    'r-packages':                '#F9795D',
    'relocation':                '#FB8560',
    'reporting':                 '#FC8F65',
    'review':                    '#FD9B6B',
    'shiny':                     '#FEA672',
    'stochastic-processes':      '#FEB179',
    'swarm':                     '#FEBC81',
    'tcg':                       '#FEC78B',
    'theoretical-science':       '#FED294',
    'travel':                    '#FDDC9E',
    'versioning':                '#FDE2A4',
    'visualization':             '#FDE7A9',
    'web-dev':                   '#FCF2B4',
    'workflow-visualization':    '#FCFDBF',
  },

  inferno: {
    '3d-printing':               '#000004',
    'a2a-protocol':              '#02020E',
    'alchemy':                   '#07051B',
    'animal-training':           '#0D0828',
    'blender':                   '#150B36',
    'bushcraft':                 '#1D0C44',
    'compliance':                '#270B52',
    'containerization':          '#320A5D',
    'crafting':                  '#3C0964',
    'data-serialization':        '#460A69',
    'defensive':                 '#500D6C',
    'design':                    '#59106E',
    'devops':                    '#62146E',
    'diffusion':                 '#6C186E',
    'esoteric':                  '#751B6E',
    'gardening':                 '#7F1E6C',
    'general':                   '#88226A',
    'geometry':                  '#922568',
    'git':                       '#9B2964',
    'hildegard':                 '#A42C60',
    'intellectual-property':     '#AE305C',
    'jigsawr':                   '#B73557',
    'lapidary':                  '#BC3855',
    'library-science':           '#C03A52',
    'maintenance':               '#C73E4C',
    'mcp-integration':           '#CF4446',
    'mlops':                     '#D74B3F',
    'morphic':                   '#DE5238',
    'mycology':                  '#E45A31',
    'number-theory':             '#E75F2E',
    'observability':             '#EA632A',
    'project-management':        '#EF6C23',
    'prospecting':               '#F3761B',
    'r-packages':                '#F68013',
    'relocation':                '#F98B0B',
    'reporting':                 '#FB9506',
    'review':                    '#FCA008',
    'shiny':                     '#FCAB10',
    'stochastic-processes':      '#FBB71B',
    'swarm':                     '#FAC329',
    'tcg':                       '#F8CE38',
    'theoretical-science':       '#F5DA4A',
    'travel':                    '#F3E55E',
    'versioning':                '#F2EA6A',
    'visualization':             '#F1EF76',
    'web-dev':                   '#F4F88E',
    'workflow-visualization':    '#FCFFA4',
  },

  plasma: {
    '3d-printing':               '#0D0887',
    'a2a-protocol':              '#1D068E',
    'alchemy':                   '#2A0593',
    'animal-training':           '#350498',
    'blender':                   '#3F049C',
    'bushcraft':                 '#4903A0',
    'compliance':                '#5202A3',
    'containerization':          '#5C01A5',
    'crafting':                  '#6500A7',
    'data-serialization':        '#6E00A8',
    'defensive':                 '#7701A8',
    'design':                    '#8004A8',
    'devops':                    '#8808A6',
    'diffusion':                 '#910EA3',
    'esoteric':                  '#99159F',
    'gardening':                 '#A11B9B',
    'general':                   '#A82296',
    'geometry':                  '#B02991',
    'git':                       '#B6308B',
    'hildegard':                 '#BD3686',
    'intellectual-property':     '#C33D80',
    'jigsawr':                   '#C9447A',
    'lapidary':                  '#CB4778',
    'library-science':           '#CD4A76',
    'maintenance':               '#D35271',
    'mcp-integration':           '#D8576B',
    'mlops':                     '#DD5E66',
    'morphic':                   '#E26561',
    'mycology':                  '#E66C5C',
    'number-theory':             '#E8705A',
    'observability':             '#EA7457',
    'project-management':        '#EE7B51',
    'prospecting':               '#F1834C',
    'r-packages':                '#F58B47',
    'relocation':                '#F79342',
    'reporting':                 '#FA9B3D',
    'review':                    '#FCA238',
    'shiny':                     '#FDAC33',
    'stochastic-processes':      '#FDB42F',
    'swarm':                     '#FEBD2A',
    'tcg':                       '#FDC727',
    'theoretical-science':       '#FCD125',
    'travel':                    '#FADA24',
    'versioning':                '#F9DF25',
    'visualization':             '#F7E425',
    'web-dev':                   '#F3EE27',
    'workflow-visualization':    '#F0F921',
  },

  cividis: {
    '3d-printing':               '#00204D',
    'a2a-protocol':              '#002557',
    'alchemy':                   '#002961',
    'animal-training':           '#002D6C',
    'blender':                   '#00306F',
    'bushcraft':                 '#00356E',
    'compliance':                '#14396D',
    'containerization':          '#223E6C',
    'crafting':                  '#2C416C',
    'data-serialization':        '#34456B',
    'defensive':                 '#3C4A6B',
    'design':                    '#424E6B',
    'devops':                    '#49526B',
    'diffusion':                 '#4F576C',
    'esoteric':                  '#555B6D',
    'gardening':                 '#5A5F6D',
    'general':                   '#60646F',
    'geometry':                  '#656870',
    'git':                       '#6B6C71',
    'hildegard':                 '#707173',
    'intellectual-property':     '#757575',
    'jigsawr':                   '#7A7A78',
    'lapidary':                  '#7D7C78',
    'library-science':           '#7F7D78',
    'maintenance':               '#848279',
    'mcp-integration':           '#8A8779',
    'mlops':                     '#908B79',
    'morphic':                   '#969078',
    'mycology':                  '#9C9577',
    'number-theory':             '#9F9877',
    'observability':             '#A29A76',
    'project-management':        '#A99F75',
    'prospecting':               '#AFA473',
    'r-packages':                '#B5A971',
    'relocation':                '#BBAE6F',
    'reporting':                 '#C2B36D',
    'review':                    '#C8B86A',
    'shiny':                     '#CFBC67',
    'stochastic-processes':      '#D5C264',
    'swarm':                     '#DBC761',
    'tcg':                       '#E2CD5C',
    'theoretical-science':       '#E9D358',
    'travel':                    '#F0D852',
    'versioning':                '#F4DB4F',
    'visualization':             '#F7DE4C',
    'web-dev':                   '#FEE445',
    'workflow-visualization':    '#FFEA46',
  },

  mako: {
    '3d-printing':               '#03051A',
    'a2a-protocol':              '#0A091F',
    'alchemy':                   '#130D25',
    'animal-training':           '#1B112B',
    'blender':                   '#241432',
    'bushcraft':                 '#2C1738',
    'compliance':                '#34193E',
    'containerization':          '#3E1B42',
    'crafting':                  '#471C48',
    'data-serialization':        '#501D4C',
    'defensive':                 '#5A1E50',
    'design':                    '#631F53',
    'devops':                    '#6D1F56',
    'diffusion':                 '#761F58',
    'esoteric':                  '#811E5A',
    'gardening':                 '#8B1D5B',
    'general':                   '#951C5B',
    'geometry':                  '#9F1A5B',
    'git':                       '#AA185A',
    'hildegard':                 '#B31658',
    'intellectual-property':     '#BD1656',
    'jigsawr':                   '#C61951',
    'lapidary':                  '#CA1B50',
    'library-science':           '#CE1D4E',
    'maintenance':               '#D62449',
    'mcp-integration':           '#DD2D45',
    'mlops':                     '#E33741',
    'morphic':                   '#E8403E',
    'mycology':                  '#EC4C3E',
    'number-theory':             '#EE523F',
    'observability':             '#EF5840',
    'project-management':        '#F16445',
    'prospecting':               '#F26F4C',
    'r-packages':                '#F47A54',
    'relocation':                '#F4845D',
    'reporting':                 '#F58F65',
    'review':                    '#F5986F',
    'shiny':                     '#F6A279',
    'stochastic-processes':      '#F6AC84',
    'swarm':                     '#F6B590',
    'tcg':                       '#F6BE9C',
    'theoretical-science':       '#F7C8A9',
    'travel':                    '#F7D0B6',
    'versioning':                '#F8D5BD',
    'visualization':             '#F8D9C3',
    'web-dev':                   '#F9E2D0',
    'workflow-visualization':    '#FAEBDD',
  },

  rocket: {
    '3d-printing':               '#0B0405',
    'a2a-protocol':              '#12080D',
    'alchemy':                   '#180D16',
    'animal-training':           '#1E111F',
    'blender':                   '#241627',
    'bushcraft':                 '#291A31',
    'compliance':                '#2E1E3A',
    'containerization':          '#332344',
    'crafting':                  '#37284E',
    'data-serialization':        '#3A2C58',
    'defensive':                 '#3C3163',
    'design':                    '#3F366E',
    'devops':                    '#403B78',
    'diffusion':                 '#414082',
    'esoteric':                  '#40478B',
    'gardening':                 '#3E4D93',
    'general':                   '#3C5598',
    'geometry':                  '#3A5C9B',
    'git':                       '#38639D',
    'hildegard':                 '#366A9F',
    'intellectual-property':     '#3671A0',
    'jigsawr':                   '#3577A2',
    'lapidary':                  '#357AA3',
    'library-science':           '#357DA3',
    'maintenance':               '#3484A5',
    'mcp-integration':           '#348BA6',
    'mlops':                     '#3491A8',
    'morphic':                   '#3498A9',
    'mycology':                  '#359FAB',
    'number-theory':             '#36A2AC',
    'observability':             '#37A5AC',
    'project-management':        '#39ACAC',
    'prospecting':               '#3DB3AD',
    'r-packages':                '#42B9AD',
    'relocation':                '#48C0AD',
    'reporting':                 '#50C6AD',
    'review':                    '#5ACDAD',
    'shiny':                     '#69D2AD',
    'stochastic-processes':      '#7AD6AE',
    'swarm':                     '#8CDBB2',
    'tcg':                       '#9DDEB7',
    'theoretical-science':       '#ACE2BF',
    'travel':                    '#B9E6C7',
    'versioning':                '#C0E9CC',
    'visualization':             '#C6EBD1',
    'web-dev':                   '#D2F0DB',
    'workflow-visualization':    '#DEF5E5',
  },

  turbo: {
    '3d-printing':               '#30123B',
    'a2a-protocol':              '#372466',
    'alchemy':                   '#3D358A',
    'animal-training':           '#4145AB',
    'blender':                   '#4455C6',
    'bushcraft':                 '#4665DC',
    'compliance':                '#4775ED',
    'containerization':          '#4684F9',
    'crafting':                  '#4392FE',
    'data-serialization':        '#3BA1FD',
    'defensive':                 '#30B0F5',
    'design':                    '#27BEE9',
    'devops':                    '#1ECBDA',
    'diffusion':                 '#18D7CA',
    'esoteric':                  '#19E2BB',
    'gardening':                 '#20EAAC',
    'general':                   '#2FF19B',
    'geometry':                  '#42F787',
    'git':                       '#58FB74',
    'hildegard':                 '#70FE60',
    'intellectual-property':     '#87FF4F',
    'jigsawr':                   '#9BFE41',
    'lapidary':                  '#A3FD3D',
    'library-science':           '#AAFB39',
    'maintenance':               '#BAF635',
    'mcp-integration':           '#C9EE34',
    'mlops':                     '#D8E535',
    'morphic':                   '#E3DB38',
    'mycology':                  '#EECF3A',
    'number-theory':             '#F2C93A',
    'observability':             '#F6C33A',
    'project-management':        '#FBB637',
    'prospecting':               '#FEA732',
    'r-packages':                '#FE972B',
    'relocation':                '#FC8523',
    'reporting':                 '#F8731C',
    'review':                    '#F26114',
    'shiny':                     '#EB510E',
    'stochastic-processes':      '#E3440A',
    'swarm':                     '#D93807',
    'tcg':                       '#CD2C04',
    'theoretical-science':       '#C02202',
    'travel':                    '#B11A01',
    'versioning':                '#A91601',
    'visualization':             '#A11201',
    'web-dev':                   '#8E0A01',
    'workflow-visualization':    '#7A0403',
  },
};

// ── Active theme state ──────────────────────────────────────────────
let currentTheme = 'cyberpunk';

export function getColor(domain) {
  return PALETTES[currentTheme]?.[domain] || '#ffffff';
}

export function setTheme(name) {
  if (PALETTES[name]) {
    currentTheme = name;
  }
}

export function getCurrentPalette() {
  return { ...PALETTES[currentTheme] };
}

export function getThemeNames() {
  return Object.keys(PALETTES);
}

export function getCurrentThemeName() {
  return currentTheme;
}

// ── Backward-compatible DOMAIN_COLORS Proxy ─────────────────────────
// Existing code reads DOMAIN_COLORS[domain]; this Proxy delegates to
// the active palette so theme switches propagate without code changes.
export const DOMAIN_COLORS = new Proxy({}, {
  get(_target, prop) {
    if (typeof prop === 'string') {
      return PALETTES[currentTheme]?.[prop];
    }
    return undefined;
  },
  ownKeys() {
    return DOMAIN_ORDER;
  },
  getOwnPropertyDescriptor(_target, prop) {
    if (DOMAIN_ORDER.includes(prop)) {
      return { configurable: true, enumerable: true, value: PALETTES[currentTheme]?.[prop] };
    }
    return undefined;
  },
  has(_target, prop) {
    return DOMAIN_ORDER.includes(prop);
  },
});

// ── Per-agent per-palette colors ─────────────────────────────────
const AGENT_PALETTE_COLORS = {
  cyberpunk: {
    'auditor':                       '#ff7744',
    'code-reviewer':                 '#ff66aa',
    'designer':                      '#ff88dd',
    'dog-trainer':                   '#ff9944',
    'devops-engineer':               '#00ff88',
    'gxp-validator':                 '#ff3399',
    'jigsawr-developer':             '#22ddaa',
    'librarian':                     '#8B7355',
    'martial-artist':                '#ff4466',
    'mlops-engineer':                '#bb77ff',
    'mycologist':                    '#aa77cc',
    'mystic':                        '#dd44ff',
    'project-manager':               '#ff8844',
    'prospector':                    '#ddaa33',
    'putior-integrator':             '#66dd88',
    'r-developer':                   '#00f0ff',
    'security-analyst':              '#ff3333',
    'shiny-developer':               '#3399ff',
    'senior-data-scientist':         '#aa66ff',
    'senior-researcher':             '#ffaa00',
    'senior-software-developer':     '#44ddff',
    'senior-ux-ui-specialist':       '#66ffcc',
    'senior-web-designer':           '#ffdd00',
    'shaman':                        '#9944ff',
    'shapeshifter':                  '#bb88ff',
    'survivalist':                   '#88cc44',
    'swarm-strategist':              '#aadd44',
    'web-developer':                 '#ff6633',
  },

  viridis: {
    'auditor':                       '#482576',
    'code-reviewer':                 '#46307E',
    'designer':                      '#433D84',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#3F4889',
    'gxp-validator':                 '#3B528B',
    'jigsawr-developer':             '#365D8D',
    'librarian':                     '#888888',
    'martial-artist':                '#31678E',
    'mlops-engineer':                '#2D718E',
    'mycologist':                    '#888888',
    'mystic':                        '#29798E',
    'project-manager':               '#26828E',
    'prospector':                    '#888888',
    'putior-integrator':             '#228C8D',
    'r-developer':                   '#1F948C',
    'security-analyst':              '#1F9E89',
    'shiny-developer':               '#20A387',
    'senior-data-scientist':         '#22A785',
    'senior-researcher':             '#29AF7F',
    'senior-software-developer':     '#37B878',
    'senior-ux-ui-specialist':       '#48C16E',
    'senior-web-designer':           '#5BC863',
    'shaman':                        '#888888',
    'shapeshifter':                  '#71CF57',
    'survivalist':                   '#89D548',
    'swarm-strategist':              '#A2DA37',
    'web-developer':                 '#BBDF27',
  },

  magma: {
    'auditor':                       '#150E37',
    'code-reviewer':                 '#21114E',
    'designer':                      '#311165',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#410F75',
    'gxp-validator':                 '#51127C',
    'jigsawr-developer':             '#601880',
    'librarian':                     '#888888',
    'martial-artist':                '#6F1F81',
    'mlops-engineer':                '#7F2582',
    'mycologist':                    '#888888',
    'mystic':                        '#8F2A81',
    'project-manager':               '#9E2F7F',
    'prospector':                    '#888888',
    'putior-integrator':             '#AE347B',
    'r-developer':                   '#BE3977',
    'security-analyst':              '#CD4071',
    'shiny-developer':               '#D5446D',
    'senior-data-scientist':         '#DC4869',
    'senior-researcher':             '#E85362',
    'senior-software-developer':     '#F2625D',
    'senior-ux-ui-specialist':       '#F8745C',
    'senior-web-designer':           '#FB8661',
    'shaman':                        '#888888',
    'shapeshifter':                  '#FD9969',
    'survivalist':                   '#FEAA74',
    'swarm-strategist':              '#FEBD82',
    'web-developer':                 '#FECE91',
  },

  inferno: {
    'auditor':                       '#170C3A',
    'code-reviewer':                 '#260C51',
    'designer':                      '#380962',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#480B6A',
    'gxp-validator':                 '#58106E',
    'jigsawr-developer':             '#67166E',
    'librarian':                     '#888888',
    'martial-artist':                '#771C6D',
    'mlops-engineer':                '#86216B',
    'mycologist':                    '#888888',
    'mystic':                        '#962667',
    'project-manager':               '#A52C60',
    'prospector':                    '#888888',
    'putior-integrator':             '#B43359',
    'r-developer':                   '#C23A50',
    'security-analyst':              '#CF4446',
    'shiny-developer':               '#D54A40',
    'senior-data-scientist':         '#DB503B',
    'senior-researcher':             '#E65D30',
    'senior-software-developer':     '#EE6A24',
    'senior-ux-ui-specialist':       '#F57B17',
    'senior-web-designer':           '#F98C0A',
    'shaman':                        '#888888',
    'shapeshifter':                  '#FB9E07',
    'survivalist':                   '#FCB014',
    'swarm-strategist':              '#FAC429',
    'web-developer':                 '#F6D645',
  },

  plasma: {
    'auditor':                       '#42049E',
    'code-reviewer':                 '#5102A3',
    'designer':                      '#6100A7',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#7000A8',
    'gxp-validator':                 '#7F03A8',
    'jigsawr-developer':             '#8D0BA5',
    'librarian':                     '#888888',
    'martial-artist':                '#9A169F',
    'mlops-engineer':                '#A62098',
    'mycologist':                    '#888888',
    'mystic':                        '#B22B8F',
    'project-manager':               '#BD3786',
    'prospector':                    '#888888',
    'putior-integrator':             '#C7427C',
    'r-developer':                   '#CF4C74',
    'security-analyst':              '#D8576B',
    'shiny-developer':               '#DC5D67',
    'senior-data-scientist':         '#E06363',
    'senior-researcher':             '#E76F5B',
    'senior-software-developer':     '#ED7A52',
    'senior-ux-ui-specialist':       '#F3874A',
    'senior-web-designer':           '#F89441',
    'shaman':                        '#888888',
    'shapeshifter':                  '#FBA139',
    'survivalist':                   '#FDAF31',
    'swarm-strategist':              '#FEBE2A',
    'web-developer':                 '#FCCE25',
  },

  cividis: {
    'auditor':                       '#00326F',
    'code-reviewer':                 '#13386D',
    'designer':                      '#28406C',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#36476B',
    'gxp-validator':                 '#414D6B',
    'jigsawr-developer':             '#4C546C',
    'librarian':                     '#888888',
    'martial-artist':                '#565C6D',
    'mlops-engineer':                '#5F636E',
    'mycologist':                    '#888888',
    'mystic':                        '#676970',
    'project-manager':               '#707173',
    'prospector':                    '#888888',
    'putior-integrator':             '#787877',
    'r-developer':                   '#817F79',
    'security-analyst':              '#8A8779',
    'shiny-developer':               '#8F8B78',
    'senior-data-scientist':         '#948E78',
    'senior-researcher':             '#9E9677',
    'senior-software-developer':     '#A89E75',
    'senior-ux-ui-specialist':       '#B2A672',
    'senior-web-designer':           '#BCAF6F',
    'shaman':                        '#888888',
    'shapeshifter':                  '#C6B66B',
    'survivalist':                   '#D1BF66',
    'swarm-strategist':              '#DCC860',
    'web-developer':                 '#E7D159',
  },

  mako: {
    'auditor':                       '#261433',
    'code-reviewer':                 '#34193D',
    'designer':                      '#431C46',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#521E4D',
    'gxp-validator':                 '#621F53',
    'jigsawr-developer':             '#711F57',
    'librarian':                     '#888888',
    'martial-artist':                '#821E5A',
    'mlops-engineer':                '#931C5B',
    'mycologist':                    '#888888',
    'mystic':                        '#A3195B',
    'project-manager':               '#B41658',
    'prospector':                    '#888888',
    'putior-integrator':             '#C31753',
    'r-developer':                   '#D11F4C',
    'security-analyst':              '#DD2C45',
    'shiny-developer':               '#E23442',
    'senior-data-scientist':         '#E73D3F',
    'senior-researcher':             '#ED4F3E',
    'senior-software-developer':     '#F16244',
    'senior-ux-ui-specialist':       '#F37450',
    'senior-web-designer':           '#F4855E',
    'shaman':                        '#888888',
    'shapeshifter':                  '#F5966D',
    'survivalist':                   '#F6A67E',
    'swarm-strategist':              '#F6B591',
    'web-developer':                 '#F7C5A5',
  },

  rocket: {
    'auditor':                       '#26172A',
    'code-reviewer':                 '#2E1E39',
    'designer':                      '#35254A',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#3B2D5A',
    'gxp-validator':                 '#3E356C',
    'jigsawr-developer':             '#413E7D',
    'librarian':                     '#888888',
    'martial-artist':                '#40488D',
    'mlops-engineer':                '#3D5297',
    'mycologist':                    '#888888',
    'mystic':                        '#395E9C',
    'project-manager':               '#366A9F',
    'prospector':                    '#888888',
    'putior-integrator':             '#3575A1',
    'r-developer':                   '#347FA4',
    'security-analyst':              '#348BA6',
    'shiny-developer':               '#3490A8',
    'senior-data-scientist':         '#3496A9',
    'senior-researcher':             '#35A1AB',
    'senior-software-developer':     '#39ABAC',
    'senior-ux-ui-specialist':       '#3FB6AD',
    'senior-web-designer':           '#49C1AD',
    'shaman':                        '#888888',
    'shapeshifter':                  '#58CBAD',
    'survivalist':                   '#70D4AD',
    'swarm-strategist':              '#8DDBB3',
    'web-developer':                 '#A8E1BC',
  },

  turbo: {
    'auditor':                       '#455BCD',
    'code-reviewer':                 '#4774EC',
    'designer':                      '#458CFD',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#39A4FB',
    'gxp-validator':                 '#28BDEA',
    'jigsawr-developer':             '#1AD2D2',
    'librarian':                     '#888888',
    'martial-artist':                '#19E3BA',
    'mlops-engineer':                '#2BEFA0',
    'mycologist':                    '#888888',
    'mystic':                        '#4BF87F',
    'project-manager':               '#71FE5F',
    'prospector':                    '#888888',
    'putior-integrator':             '#95FE45',
    'r-developer':                   '#B0FA37',
    'security-analyst':              '#C8EF34',
    'shiny-developer':               '#D4E736',
    'senior-data-scientist':         '#DFDF37',
    'senior-researcher':             '#F0CC3A',
    'senior-software-developer':     '#FBB838',
    'senior-ux-ui-specialist':       '#FE9E2F',
    'senior-web-designer':           '#FB8222',
    'shaman':                        '#888888',
    'shapeshifter':                  '#F46516',
    'survivalist':                   '#E84B0C',
    'swarm-strategist':              '#D83706',
    'web-developer':                 '#C42503',
  },
};

export function getAgentColor(agentId) {
  if (agentId && AGENT_PALETTE_COLORS[currentTheme]?.[agentId]) {
    return AGENT_PALETTE_COLORS[currentTheme][agentId];
  }
  // Fallback: first agent color in current palette, or gold
  const colors = AGENT_PALETTE_COLORS[currentTheme];
  if (colors) {
    const vals = Object.values(colors);
    return vals[0] || '#ffd700';
  }
  return '#ffd700';
}

export const AGENT_PRIORITY_CONFIG = {
  critical: { radius: 8, glowRadius: 24, glowOpacity: 0.7 },
  high:     { radius: 6, glowRadius: 18, glowOpacity: 0.5 },
  normal:   { radius: 5, glowRadius: 14, glowOpacity: 0.4 },
};

// ── Per-team per-palette colors ──────────────────────────────────
const TEAM_PALETTE_COLORS = {
  cyberpunk: {
    'ai-self-care':                  '#da70d6',
    'devops-platform-engineering':   '#ff4500',
    'fullstack-web-dev':             '#ffcc00',
    'gxp-compliance-validation':     '#ff6ec7',
    'ml-data-science-review':        '#7b68ee',
    'opaque-team':                   '#bb88ff',
    'r-package-review':              '#00ccff',
    'scrum-team':                    '#ff8844',
  },

  viridis: {
    'ai-self-care':                  '#35608D',
    'devops-platform-engineering':   '#2E6E8E',
    'fullstack-web-dev':             '#287C8E',
    'gxp-compliance-validation':     '#23898E',
    'ml-data-science-review':        '#1F978B',
    'opaque-team':                   '#20A486',
    'r-package-review':              '#2DB27D',
    'scrum-team':                    '#43BF71',
  },

  magma: {
    'ai-self-care':                  '#641A80',
    'devops-platform-engineering':   '#7B2382',
    'fullstack-web-dev':             '#922B80',
    'gxp-compliance-validation':     '#AA337D',
    'ml-data-science-review':        '#C13B75',
    'opaque-team':                   '#D8456C',
    'r-package-review':              '#EB5760',
    'scrum-team':                    '#F76F5C',
  },

  inferno: {
    'ai-self-care':                  '#6B186E',
    'devops-platform-engineering':   '#82206C',
    'fullstack-web-dev':             '#992865',
    'gxp-compliance-validation':     '#B0315B',
    'ml-data-science-review':        '#C63D4D',
    'opaque-team':                   '#D84C3E',
    'r-package-review':              '#E8602D',
    'scrum-team':                    '#F3771A',
  },

  plasma: {
    'ai-self-care':                  '#900DA4',
    'devops-platform-engineering':   '#A31E9A',
    'fullstack-web-dev':             '#B52F8C',
    'gxp-compliance-validation':     '#C43E7F',
    'ml-data-science-review':        '#D24F71',
    'opaque-team':                   '#DE6065',
    'r-package-review':              '#E97158',
    'scrum-team':                    '#F1844B',
  },

  cividis: {
    'ai-self-care':                  '#4E576C',
    'devops-platform-engineering':   '#5C616E',
    'fullstack-web-dev':             '#6A6C71',
    'gxp-compliance-validation':     '#767676',
    'ml-data-science-review':        '#848179',
    'opaque-team':                   '#918C78',
    'r-package-review':              '#A09877',
    'scrum-team':                    '#B0A473',
  },

  mako: {
    'ai-self-care':                  '#751F58',
    'devops-platform-engineering':   '#8E1D5B',
    'fullstack-web-dev':             '#A7185A',
    'gxp-compliance-validation':     '#C01654',
    'ml-data-science-review':        '#D5224A',
    'opaque-team':                   '#E43841',
    'r-package-review':              '#EE543F',
    'scrum-team':                    '#F2704D',
  },

  rocket: {
    'ai-self-care':                  '#414081',
    'devops-platform-engineering':   '#3E5095',
    'fullstack-web-dev':             '#38629D',
    'gxp-compliance-validation':     '#3572A1',
    'ml-data-science-review':        '#3483A5',
    'opaque-team':                   '#3492A8',
    'r-package-review':              '#36A3AB',
    'scrum-team':                    '#3DB4AD',
  },

  turbo: {
    'ai-self-care':                  '#18D6CB',
    'devops-platform-engineering':   '#25ECA7',
    'fullstack-web-dev':             '#54FA77',
    'gxp-compliance-validation':     '#8CFF4A',
    'ml-data-science-review':        '#B6F735',
    'opaque-team':                   '#DAE336',
    'r-package-review':              '#F4C73A',
    'scrum-team':                    '#FEA632',
  },
};

export function getTeamColor(teamId) {
  if (teamId && TEAM_PALETTE_COLORS[currentTheme]?.[teamId]) {
    return TEAM_PALETTE_COLORS[currentTheme][teamId];
  }
  const colors = TEAM_PALETTE_COLORS[currentTheme];
  if (colors) {
    const vals = Object.values(colors);
    return vals[0] || '#00ffcc';
  }
  return '#00ffcc';
}

export const TEAM_CONFIG = {
  radius: 7,
  glowRadius: 20,
  glowOpacity: 0.55,
};

// ── Complexity configs (unchanged) ──────────────────────────────────
export const COMPLEXITY_CONFIG = {
  basic:        { radius: 5, glowRadius: 14, glowOpacity: 0.4,  label: 'Basic' },
  intermediate: { radius: 5, glowRadius: 18, glowOpacity: 0.5,  label: 'Intermediate' },
  advanced:     { radius: 5, glowRadius: 22, glowOpacity: 0.6,  label: 'Advanced' },
};

export const COMPLEXITY_BADGE_COLORS = {
  basic:        '#00ff88',
  intermediate: '#ffdd00',
  advanced:     '#dd44ff',
};

// ── Featured hub nodes (viz-layer config, not skill metadata) ────────
export const FEATURED_NODES = {
  'create-skill':        { radius: 9, tier: 'primary' },
  'evolve-skill':        { radius: 7, tier: 'secondary' },
  'create-skill-glyph':  { radius: 7, tier: 'secondary' },
};

const _rgbaCache = new Map();
export function hexToRgba(hex, alpha) {
  const key = hex + '|' + alpha;
  let val = _rgbaCache.get(key);
  if (val !== undefined) return val;
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  val = `rgba(${r},${g},${b},${alpha})`;
  _rgbaCache.set(key, val);
  return val;
}
