/**
 * colors.js - Theme palette system with 9 switchable colormaps
 *
 * Provides: getColor, setTheme, getCurrentPalette, getThemeNames
 * Backward compat: DOMAIN_COLORS Proxy delegates to active palette
 */

// ── Domain order (alphabetical) for consistent palette assignment ──
const DOMAIN_ORDER = [
  'a2a-protocol',
  'alchemy',
  'animal-training',
  'bushcraft',
  'compliance',
  'containerization',
  'crafting',
  'data-serialization',
  'defensive',
  'design',
  'devops',
  'diffusion',
  'esoteric',
  'gardening',
  'general',
  'geometry',
  'git',
  'intellectual-property',
  'jigsawr',
  'library-science',
  'mcp-integration',
  'mlops',
  'morphic',
  'mycology',
  'observability',
  'project-management',
  'prospecting',
  'r-packages',
  'relocation',
  'reporting',
  'review',
  'shiny',
  'stochastic-processes',
  'swarm',
  'tcg',
  'theoretical-science',
  'travel',
  'web-dev',
  'workflow-visualization',
];

// ── 9 named palettes: one hex color per domain (22 domains) ────────
const PALETTES = {
  cyberpunk: {
    'a2a-protocol':              '#44bbaa',
    'alchemy':                   '#ffaa33',
    'animal-training':           '#ff9944',
    'bushcraft':                 '#88cc44',
    'compliance':                '#ff3366',
    'containerization':          '#44ddff',
    'crafting':                  '#cc8855',
    'data-serialization':        '#44aaff',
    'defensive':                 '#ff4444',
    'design':                    '#ff88dd',
    'devops':                    '#00ff88',
    'diffusion':                 '#cc77ff',
    'esoteric':                  '#dd44ff',
    'gardening':                 '#44bb66',
    'general':                   '#ccccff',
    'geometry':                  '#55ccdd',
    'git':                       '#66ffcc',
    'intellectual-property':     '#33ccff',
    'jigsawr':                   '#22ddaa',
    'library-science':           '#8B7355',
    'mcp-integration':           '#00ccaa',
    'mlops':                     '#aa66ff',
    'morphic':                   '#bb88ff',
    'mycology':                  '#aa77cc',
    'observability':             '#ffaa00',
    'project-management':        '#ff8844',
    'prospecting':               '#ddaa33',
    'r-packages':                '#00f0ff',
    'relocation':                '#ff9977',
    'reporting':                 '#ffdd00',
    'review':                    '#ff66aa',
    'shiny':                     '#3399ff',
    'stochastic-processes':      '#77aaff',
    'swarm':                     '#aadd44',
    'tcg':                       '#ff5577',
    'theoretical-science':       '#ddbb55',
    'travel':                    '#66cc99',
    'web-dev':                   '#ff6633',
    'workflow-visualization':    '#66dd88',
  },

  viridis: {
    'a2a-protocol':              '#440154',
    'alchemy':                   '#460B5E',
    'animal-training':           '#481568',
    'bushcraft':                 '#481D6F',
    'compliance':                '#482677',
    'containerization':          '#472F7D',
    'crafting':                  '#453781',
    'data-serialization':        '#423F85',
    'defensive':                 '#3F4788',
    'design':                    '#3D4E8A',
    'devops':                    '#39558C',
    'diffusion':                 '#365D8D',
    'esoteric':                  '#32648E',
    'gardening':                 '#306A8E',
    'general':                   '#2D718E',
    'geometry':                  '#2A778E',
    'git':                       '#287D8E',
    'intellectual-property':     '#25838E',
    'jigsawr':                   '#238A8D',
    'library-science':           '#21908C',
    'mcp-integration':           '#1F968B',
    'mlops':                     '#1E9D89',
    'morphic':                   '#20A386',
    'mycology':                  '#23A983',
    'observability':             '#29AF7F',
    'project-management':        '#32B67A',
    'prospecting':               '#3CBC75',
    'r-packages':                '#48C16E',
    'relocation':                '#56C667',
    'reporting':                 '#64CB5F',
    'review':                    '#74D055',
    'shiny':                     '#84D44B',
    'stochastic-processes':      '#94D840',
    'swarm':                     '#A6DB35',
    'tcg':                       '#B8DE29',
    'theoretical-science':       '#CAE11F',
    'travel':                    '#DCE318',
    'web-dev':                   '#EDE51B',
    'workflow-visualization':    '#FDE725',
  },

  magma: {
    'a2a-protocol':              '#000004',
    'alchemy':                   '#03030E',
    'animal-training':           '#07071D',
    'bushcraft':                 '#0E0B2B',
    'compliance':                '#160F3B',
    'containerization':          '#1F114A',
    'crafting':                  '#29115A',
    'data-serialization':        '#341069',
    'defensive':                 '#400F73',
    'design':                    '#4B1079',
    'devops':                    '#56147D',
    'diffusion':                 '#601880',
    'esoteric':                  '#6B1D81',
    'gardening':                 '#752181',
    'general':                   '#802582',
    'geometry':                  '#8A2981',
    'git':                       '#952C80',
    'intellectual-property':     '#A02F7F',
    'jigsawr':                   '#AB337C',
    'library-science':           '#B63679',
    'mcp-integration':           '#C03A76',
    'mlops':                     '#CC3F71',
    'morphic':                   '#D6456C',
    'mycology':                  '#DF4B68',
    'observability':             '#E85362',
    'project-management':        '#EF5C5E',
    'prospecting':               '#F4685C',
    'r-packages':                '#F8745C',
    'relocation':                '#FA815F',
    'reporting':                 '#FC8D64',
    'review':                    '#FD9A6A',
    'shiny':                     '#FEA772',
    'stochastic-processes':      '#FEB37B',
    'swarm':                     '#FEC084',
    'tcg':                       '#FECC8F',
    'theoretical-science':       '#FED89A',
    'travel':                    '#FDE4A6',
    'web-dev':                   '#FCF1B3',
    'workflow-visualization':    '#FCFDBF',
  },

  inferno: {
    'a2a-protocol':              '#000004',
    'alchemy':                   '#03020F',
    'animal-training':           '#08051E',
    'bushcraft':                 '#10092D',
    'compliance':                '#190C3E',
    'containerization':          '#240C4E',
    'crafting':                  '#300A5B',
    'data-serialization':        '#3B0964',
    'defensive':                 '#460B6A',
    'design':                    '#510E6C',
    'devops':                    '#5C126E',
    'diffusion':                 '#67166E',
    'esoteric':                  '#711A6E',
    'gardening':                 '#7C1D6D',
    'general':                   '#87216B',
    'geometry':                  '#912568',
    'git':                       '#9C2964',
    'intellectual-property':     '#A62D60',
    'jigsawr':                   '#B1325A',
    'library-science':           '#BB3754',
    'mcp-integration':           '#C43C4E',
    'mlops':                     '#CE4347',
    'morphic':                   '#D64B40',
    'mycology':                  '#DE5238',
    'observability':             '#E55C30',
    'project-management':        '#EB6628',
    'prospecting':               '#F17020',
    'r-packages':                '#F57B17',
    'relocation':                '#F8870E',
    'reporting':                 '#FA9307',
    'review':                    '#FCA007',
    'shiny':                     '#FCAC11',
    'stochastic-processes':      '#FBB91F',
    'swarm':                     '#FAC62E',
    'tcg':                       '#F7D340',
    'theoretical-science':       '#F4E156',
    'travel':                    '#F1ED6F',
    'web-dev':                   '#F3F78B',
    'workflow-visualization':    '#FCFFA4',
  },

  plasma: {
    'a2a-protocol':              '#0D0887',
    'alchemy':                   '#1F068F',
    'animal-training':           '#2D0594',
    'bushcraft':                 '#38049A',
    'compliance':                '#44039E',
    'containerization':          '#4F02A2',
    'crafting':                  '#5901A5',
    'data-serialization':        '#6400A7',
    'defensive':                 '#6F00A8',
    'design':                    '#7901A8',
    'devops':                    '#8305A7',
    'diffusion':                 '#8D0BA5',
    'esoteric':                  '#9512A1',
    'gardening':                 '#9E199D',
    'general':                   '#A72197',
    'geometry':                  '#AF2991',
    'git':                       '#B6308B',
    'intellectual-property':     '#BE3885',
    'jigsawr':                   '#C5407E',
    'library-science':           '#CC4678',
    'mcp-integration':           '#D14E72',
    'mlops':                     '#D7566C',
    'morphic':                   '#DD5E66',
    'mycology':                  '#E26561',
    'observability':             '#E76E5B',
    'project-management':        '#EB7655',
    'prospecting':               '#EF7F4F',
    'r-packages':                '#F3874A',
    'relocation':                '#F79044',
    'reporting':                 '#F9993E',
    'review':                    '#FBA238',
    'shiny':                     '#FDAC33',
    'stochastic-processes':      '#FEB72D',
    'swarm':                     '#FEC129',
    'tcg':                       '#FDCB26',
    'theoretical-science':       '#FBD724',
    'travel':                    '#F7E225',
    'web-dev':                   '#F4ED27',
    'workflow-visualization':    '#F0F921',
  },

  cividis: {
    'a2a-protocol':              '#00204D',
    'alchemy':                   '#002558',
    'animal-training':           '#002A64',
    'bushcraft':                 '#002E6F',
    'compliance':                '#00336F',
    'containerization':          '#0D386E',
    'crafting':                  '#1F3C6D',
    'data-serialization':        '#2B416C',
    'defensive':                 '#35466B',
    'design':                    '#3E4A6B',
    'devops':                    '#444F6B',
    'diffusion':                 '#4C546C',
    'esoteric':                  '#53596C',
    'gardening':                 '#595E6D',
    'general':                   '#5F636E',
    'geometry':                  '#656870',
    'git':                       '#6B6C71',
    'intellectual-property':     '#717174',
    'jigsawr':                   '#777776',
    'library-science':           '#7C7B78',
    'mcp-integration':           '#838079',
    'mlops':                     '#898679',
    'morphic':                   '#908B79',
    'mycology':                  '#969078',
    'observability':             '#9D9677',
    'project-management':        '#A49B76',
    'prospecting':               '#ABA074',
    'r-packages':                '#B2A672',
    'relocation':                '#B9AC70',
    'reporting':                 '#C1B26D',
    'review':                    '#C7B76B',
    'shiny':                     '#CFBD67',
    'stochastic-processes':      '#D7C463',
    'swarm':                     '#DDC95F',
    'tcg':                       '#E5D05A',
    'theoretical-science':       '#EDD654',
    'travel':                    '#F5DD4D',
    'web-dev':                   '#FDE346',
    'workflow-visualization':    '#FFEA46',
  },

  mako: {
    'a2a-protocol':              '#03051A',
    'alchemy':                   '#0B0920',
    'animal-training':           '#150E26',
    'bushcraft':                 '#1E122D',
    'compliance':                '#281535',
    'containerization':          '#32183C',
    'crafting':                  '#3C1A42',
    'data-serialization':        '#461C48',
    'defensive':                 '#511E4D',
    'design':                    '#5B1E51',
    'devops':                    '#661F54',
    'diffusion':                 '#711F57',
    'esoteric':                  '#7C1F5A',
    'gardening':                 '#871E5B',
    'general':                   '#931C5B',
    'geometry':                  '#9F1A5B',
    'git':                       '#AA185A',
    'intellectual-property':     '#B51657',
    'jigsawr':                   '#C11754',
    'library-science':           '#CB1B4F',
    'mcp-integration':           '#D3214B',
    'mlops':                     '#DC2B46',
    'morphic':                   '#E33541',
    'mycology':                  '#E8413E',
    'observability':             '#ED4E3E',
    'project-management':        '#F05C42',
    'prospecting':               '#F26847',
    'r-packages':                '#F37450',
    'relocation':                '#F4815A',
    'reporting':                 '#F58C64',
    'review':                    '#F5986F',
    'shiny':                     '#F6A37A',
    'stochastic-processes':      '#F6AE86',
    'swarm':                     '#F6B894',
    'tcg':                       '#F7C2A2',
    'theoretical-science':       '#F7CDB1',
    'travel':                    '#F8D7BF',
    'web-dev':                   '#F9E1CE',
    'workflow-visualization':    '#FAEBDD',
  },

  rocket: {
    'a2a-protocol':              '#0B0405',
    'alchemy':                   '#13090E',
    'animal-training':           '#190E19',
    'bushcraft':                 '#201322',
    'compliance':                '#27182D',
    'containerization':          '#2D1C37',
    'crafting':                  '#312142',
    'data-serialization':        '#36274D',
    'defensive':                 '#3A2C59',
    'design':                    '#3D3165',
    'devops':                    '#3F3770',
    'diffusion':                 '#413E7D',
    'esoteric':                  '#414388',
    'gardening':                 '#3F4B90',
    'general':                   '#3C5397',
    'geometry':                  '#3A5C9B',
    'git':                       '#38639D',
    'intellectual-property':     '#366B9F',
    'jigsawr':                   '#3573A1',
    'library-science':           '#357BA2',
    'mcp-integration':           '#3482A4',
    'mlops':                     '#3489A6',
    'morphic':                   '#3491A8',
    'mycology':                  '#3498A9',
    'observability':             '#35A0AB',
    'project-management':        '#37A8AC',
    'prospecting':               '#3AAEAD',
    'r-packages':                '#3FB6AD',
    'relocation':                '#46BEAD',
    'reporting':                 '#4EC5AD',
    'review':                    '#5ACCAD',
    'shiny':                     '#6AD2AD',
    'stochastic-processes':      '#7ED7AF',
    'swarm':                     '#92DBB5',
    'tcg':                       '#A4E0BB',
    'theoretical-science':       '#B5E5C4',
    'travel':                    '#C3E9CE',
    'web-dev':                   '#D1EFDA',
    'workflow-visualization':    '#DEF5E5',
  },

  turbo: {
    'a2a-protocol':              '#30123B',
    'alchemy':                   '#38266B',
    'animal-training':           '#3F3994',
    'bushcraft':                 '#424BB6',
    'compliance':                '#455ED2',
    'containerization':          '#4770E8',
    'crafting':                  '#4681F7',
    'data-serialization':        '#4391FE',
    'defensive':                 '#3AA2FC',
    'design':                    '#2FB3F3',
    'devops':                    '#23C3E4',
    'diffusion':                 '#1AD2D2',
    'esoteric':                  '#18DEC1',
    'gardening':                 '#1DE7B1',
    'general':                   '#2CF09E',
    'geometry':                  '#42F788',
    'git':                       '#5BFB72',
    'intellectual-property':     '#75FE5C',
    'jigsawr':                   '#8EFF49',
    'library-science':           '#A2FC3C',
    'mcp-integration':           '#B5F836',
    'mlops':                     '#C6F034',
    'morphic':                   '#D6E635',
    'mycology':                  '#E4DA38',
    'observability':             '#EFCD3A',
    'project-management':        '#F8BF39',
    'prospecting':               '#FCB036',
    'r-packages':                '#FE9D2F',
    'relocation':                '#FD8A26',
    'reporting':                 '#F9761D',
    'review':                    '#F36215',
    'shiny':                     '#EB500E',
    'stochastic-processes':      '#E14209',
    'swarm':                     '#D53406',
    'tcg':                       '#C82803',
    'theoretical-science':       '#B71D02',
    'travel':                    '#A51301',
    'web-dev':                   '#910B01',
    'workflow-visualization':    '#7A0403',
  },
};

// ── Active theme state ──────────────────────────────────────────────
let currentTheme = 'cyberpunk';

export function getColor(domain) {
  return PALETTES[currentTheme]?.[domain] || '#ffffff';
}

export function setTheme(name) {
  if (PALETTES[name]) {
    currentTheme = name;
  }
}

export function getCurrentPalette() {
  return { ...PALETTES[currentTheme] };
}

export function getThemeNames() {
  return Object.keys(PALETTES);
}

export function getCurrentThemeName() {
  return currentTheme;
}

// ── Backward-compatible DOMAIN_COLORS Proxy ─────────────────────────
// Existing code reads DOMAIN_COLORS[domain]; this Proxy delegates to
// the active palette so theme switches propagate without code changes.
export const DOMAIN_COLORS = new Proxy({}, {
  get(_target, prop) {
    if (typeof prop === 'string') {
      return PALETTES[currentTheme]?.[prop];
    }
    return undefined;
  },
  ownKeys() {
    return DOMAIN_ORDER;
  },
  getOwnPropertyDescriptor(_target, prop) {
    if (DOMAIN_ORDER.includes(prop)) {
      return { configurable: true, enumerable: true, value: PALETTES[currentTheme]?.[prop] };
    }
    return undefined;
  },
  has(_target, prop) {
    return DOMAIN_ORDER.includes(prop);
  },
});

// ── Per-agent per-palette colors ─────────────────────────────────
const AGENT_PALETTE_COLORS = {
  cyberpunk: {
    'auditor':                       '#ff7744',
    'code-reviewer':                 '#ff66aa',
    'designer':                      '#ff88dd',
    'dog-trainer':                   '#ff9944',
    'devops-engineer':               '#00ff88',
    'gxp-validator':                 '#ff3399',
    'jigsawr-developer':             '#22ddaa',
    'librarian':                     '#8B7355',
    'martial-artist':                '#ff4466',
    'mlops-engineer':                '#bb77ff',
    'mycologist':                    '#aa77cc',
    'mystic':                        '#dd44ff',
    'project-manager':               '#ff8844',
    'prospector':                    '#ddaa33',
    'putior-integrator':             '#66dd88',
    'r-developer':                   '#00f0ff',
    'security-analyst':              '#ff3333',
    'shiny-developer':               '#3399ff',
    'senior-data-scientist':         '#aa66ff',
    'senior-researcher':             '#ffaa00',
    'senior-software-developer':     '#44ddff',
    'senior-ux-ui-specialist':       '#66ffcc',
    'senior-web-designer':           '#ffdd00',
    'shaman':                        '#9944ff',
    'shapeshifter':                  '#bb88ff',
    'survivalist':                   '#88cc44',
    'swarm-strategist':              '#aadd44',
    'web-developer':                 '#ff6633',
  },

  viridis: {
    'auditor':                       '#482576',
    'code-reviewer':                 '#46307E',
    'designer':                      '#433D84',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#3F4889',
    'gxp-validator':                 '#3B528B',
    'jigsawr-developer':             '#365D8D',
    'librarian':                     '#888888',
    'martial-artist':                '#31678E',
    'mlops-engineer':                '#2D718E',
    'mycologist':                    '#888888',
    'mystic':                        '#29798E',
    'project-manager':               '#26828E',
    'prospector':                    '#888888',
    'putior-integrator':             '#228C8D',
    'r-developer':                   '#1F948C',
    'security-analyst':              '#1F9E89',
    'shiny-developer':               '#20A387',
    'senior-data-scientist':         '#22A785',
    'senior-researcher':             '#29AF7F',
    'senior-software-developer':     '#37B878',
    'senior-ux-ui-specialist':       '#48C16E',
    'senior-web-designer':           '#5BC863',
    'shaman':                        '#888888',
    'shapeshifter':                  '#71CF57',
    'survivalist':                   '#89D548',
    'swarm-strategist':              '#A2DA37',
    'web-developer':                 '#BBDF27',
  },

  magma: {
    'auditor':                       '#150E37',
    'code-reviewer':                 '#21114E',
    'designer':                      '#311165',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#410F75',
    'gxp-validator':                 '#51127C',
    'jigsawr-developer':             '#601880',
    'librarian':                     '#888888',
    'martial-artist':                '#6F1F81',
    'mlops-engineer':                '#7F2582',
    'mycologist':                    '#888888',
    'mystic':                        '#8F2A81',
    'project-manager':               '#9E2F7F',
    'prospector':                    '#888888',
    'putior-integrator':             '#AE347B',
    'r-developer':                   '#BE3977',
    'security-analyst':              '#CD4071',
    'shiny-developer':               '#D5446D',
    'senior-data-scientist':         '#DC4869',
    'senior-researcher':             '#E85362',
    'senior-software-developer':     '#F2625D',
    'senior-ux-ui-specialist':       '#F8745C',
    'senior-web-designer':           '#FB8661',
    'shaman':                        '#888888',
    'shapeshifter':                  '#FD9969',
    'survivalist':                   '#FEAA74',
    'swarm-strategist':              '#FEBD82',
    'web-developer':                 '#FECE91',
  },

  inferno: {
    'auditor':                       '#170C3A',
    'code-reviewer':                 '#260C51',
    'designer':                      '#380962',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#480B6A',
    'gxp-validator':                 '#58106E',
    'jigsawr-developer':             '#67166E',
    'librarian':                     '#888888',
    'martial-artist':                '#771C6D',
    'mlops-engineer':                '#86216B',
    'mycologist':                    '#888888',
    'mystic':                        '#962667',
    'project-manager':               '#A52C60',
    'prospector':                    '#888888',
    'putior-integrator':             '#B43359',
    'r-developer':                   '#C23A50',
    'security-analyst':              '#CF4446',
    'shiny-developer':               '#D54A40',
    'senior-data-scientist':         '#DB503B',
    'senior-researcher':             '#E65D30',
    'senior-software-developer':     '#EE6A24',
    'senior-ux-ui-specialist':       '#F57B17',
    'senior-web-designer':           '#F98C0A',
    'shaman':                        '#888888',
    'shapeshifter':                  '#FB9E07',
    'survivalist':                   '#FCB014',
    'swarm-strategist':              '#FAC429',
    'web-developer':                 '#F6D645',
  },

  plasma: {
    'auditor':                       '#42049E',
    'code-reviewer':                 '#5102A3',
    'designer':                      '#6100A7',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#7000A8',
    'gxp-validator':                 '#7F03A8',
    'jigsawr-developer':             '#8D0BA5',
    'librarian':                     '#888888',
    'martial-artist':                '#9A169F',
    'mlops-engineer':                '#A62098',
    'mycologist':                    '#888888',
    'mystic':                        '#B22B8F',
    'project-manager':               '#BD3786',
    'prospector':                    '#888888',
    'putior-integrator':             '#C7427C',
    'r-developer':                   '#CF4C74',
    'security-analyst':              '#D8576B',
    'shiny-developer':               '#DC5D67',
    'senior-data-scientist':         '#E06363',
    'senior-researcher':             '#E76F5B',
    'senior-software-developer':     '#ED7A52',
    'senior-ux-ui-specialist':       '#F3874A',
    'senior-web-designer':           '#F89441',
    'shaman':                        '#888888',
    'shapeshifter':                  '#FBA139',
    'survivalist':                   '#FDAF31',
    'swarm-strategist':              '#FEBE2A',
    'web-developer':                 '#FCCE25',
  },

  cividis: {
    'auditor':                       '#00326F',
    'code-reviewer':                 '#13386D',
    'designer':                      '#28406C',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#36476B',
    'gxp-validator':                 '#414D6B',
    'jigsawr-developer':             '#4C546C',
    'librarian':                     '#888888',
    'martial-artist':                '#565C6D',
    'mlops-engineer':                '#5F636E',
    'mycologist':                    '#888888',
    'mystic':                        '#676970',
    'project-manager':               '#707173',
    'prospector':                    '#888888',
    'putior-integrator':             '#787877',
    'r-developer':                   '#817F79',
    'security-analyst':              '#8A8779',
    'shiny-developer':               '#8F8B78',
    'senior-data-scientist':         '#948E78',
    'senior-researcher':             '#9E9677',
    'senior-software-developer':     '#A89E75',
    'senior-ux-ui-specialist':       '#B2A672',
    'senior-web-designer':           '#BCAF6F',
    'shaman':                        '#888888',
    'shapeshifter':                  '#C6B66B',
    'survivalist':                   '#D1BF66',
    'swarm-strategist':              '#DCC860',
    'web-developer':                 '#E7D159',
  },

  mako: {
    'auditor':                       '#261433',
    'code-reviewer':                 '#34193D',
    'designer':                      '#431C46',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#521E4D',
    'gxp-validator':                 '#621F53',
    'jigsawr-developer':             '#711F57',
    'librarian':                     '#888888',
    'martial-artist':                '#821E5A',
    'mlops-engineer':                '#931C5B',
    'mycologist':                    '#888888',
    'mystic':                        '#A3195B',
    'project-manager':               '#B41658',
    'prospector':                    '#888888',
    'putior-integrator':             '#C31753',
    'r-developer':                   '#D11F4C',
    'security-analyst':              '#DD2C45',
    'shiny-developer':               '#E23442',
    'senior-data-scientist':         '#E73D3F',
    'senior-researcher':             '#ED4F3E',
    'senior-software-developer':     '#F16244',
    'senior-ux-ui-specialist':       '#F37450',
    'senior-web-designer':           '#F4855E',
    'shaman':                        '#888888',
    'shapeshifter':                  '#F5966D',
    'survivalist':                   '#F6A67E',
    'swarm-strategist':              '#F6B591',
    'web-developer':                 '#F7C5A5',
  },

  rocket: {
    'auditor':                       '#26172A',
    'code-reviewer':                 '#2E1E39',
    'designer':                      '#35254A',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#3B2D5A',
    'gxp-validator':                 '#3E356C',
    'jigsawr-developer':             '#413E7D',
    'librarian':                     '#888888',
    'martial-artist':                '#40488D',
    'mlops-engineer':                '#3D5297',
    'mycologist':                    '#888888',
    'mystic':                        '#395E9C',
    'project-manager':               '#366A9F',
    'prospector':                    '#888888',
    'putior-integrator':             '#3575A1',
    'r-developer':                   '#347FA4',
    'security-analyst':              '#348BA6',
    'shiny-developer':               '#3490A8',
    'senior-data-scientist':         '#3496A9',
    'senior-researcher':             '#35A1AB',
    'senior-software-developer':     '#39ABAC',
    'senior-ux-ui-specialist':       '#3FB6AD',
    'senior-web-designer':           '#49C1AD',
    'shaman':                        '#888888',
    'shapeshifter':                  '#58CBAD',
    'survivalist':                   '#70D4AD',
    'swarm-strategist':              '#8DDBB3',
    'web-developer':                 '#A8E1BC',
  },

  turbo: {
    'auditor':                       '#455BCD',
    'code-reviewer':                 '#4774EC',
    'designer':                      '#458CFD',
    'dog-trainer':                   '#888888',
    'devops-engineer':               '#39A4FB',
    'gxp-validator':                 '#28BDEA',
    'jigsawr-developer':             '#1AD2D2',
    'librarian':                     '#888888',
    'martial-artist':                '#19E3BA',
    'mlops-engineer':                '#2BEFA0',
    'mycologist':                    '#888888',
    'mystic':                        '#4BF87F',
    'project-manager':               '#71FE5F',
    'prospector':                    '#888888',
    'putior-integrator':             '#95FE45',
    'r-developer':                   '#B0FA37',
    'security-analyst':              '#C8EF34',
    'shiny-developer':               '#D4E736',
    'senior-data-scientist':         '#DFDF37',
    'senior-researcher':             '#F0CC3A',
    'senior-software-developer':     '#FBB838',
    'senior-ux-ui-specialist':       '#FE9E2F',
    'senior-web-designer':           '#FB8222',
    'shaman':                        '#888888',
    'shapeshifter':                  '#F46516',
    'survivalist':                   '#E84B0C',
    'swarm-strategist':              '#D83706',
    'web-developer':                 '#C42503',
  },
};

export function getAgentColor(agentId) {
  if (agentId && AGENT_PALETTE_COLORS[currentTheme]?.[agentId]) {
    return AGENT_PALETTE_COLORS[currentTheme][agentId];
  }
  // Fallback: first agent color in current palette, or gold
  const colors = AGENT_PALETTE_COLORS[currentTheme];
  if (colors) {
    const vals = Object.values(colors);
    return vals[0] || '#ffd700';
  }
  return '#ffd700';
}

export const AGENT_PRIORITY_CONFIG = {
  critical: { radius: 8, glowRadius: 24, glowOpacity: 0.7 },
  high:     { radius: 6, glowRadius: 18, glowOpacity: 0.5 },
  normal:   { radius: 5, glowRadius: 14, glowOpacity: 0.4 },
};

// ── Per-team per-palette colors ──────────────────────────────────
const TEAM_PALETTE_COLORS = {
  cyberpunk: {
    'ai-self-care':                  '#da70d6',
    'devops-platform-engineering':   '#ff4500',
    'fullstack-web-dev':             '#ffcc00',
    'gxp-compliance-validation':     '#ff6ec7',
    'ml-data-science-review':        '#7b68ee',
    'opaque-team':                   '#bb88ff',
    'r-package-review':              '#00ccff',
    'scrum-team':                    '#ff8844',
  },

  viridis: {
    'ai-self-care':                  '#35608D',
    'devops-platform-engineering':   '#2E6E8E',
    'fullstack-web-dev':             '#287C8E',
    'gxp-compliance-validation':     '#23898E',
    'ml-data-science-review':        '#1F978B',
    'opaque-team':                   '#20A486',
    'r-package-review':              '#2DB27D',
    'scrum-team':                    '#43BF71',
  },

  magma: {
    'ai-self-care':                  '#641A80',
    'devops-platform-engineering':   '#7B2382',
    'fullstack-web-dev':             '#922B80',
    'gxp-compliance-validation':     '#AA337D',
    'ml-data-science-review':        '#C13B75',
    'opaque-team':                   '#D8456C',
    'r-package-review':              '#EB5760',
    'scrum-team':                    '#F76F5C',
  },

  inferno: {
    'ai-self-care':                  '#6B186E',
    'devops-platform-engineering':   '#82206C',
    'fullstack-web-dev':             '#992865',
    'gxp-compliance-validation':     '#B0315B',
    'ml-data-science-review':        '#C63D4D',
    'opaque-team':                   '#D84C3E',
    'r-package-review':              '#E8602D',
    'scrum-team':                    '#F3771A',
  },

  plasma: {
    'ai-self-care':                  '#900DA4',
    'devops-platform-engineering':   '#A31E9A',
    'fullstack-web-dev':             '#B52F8C',
    'gxp-compliance-validation':     '#C43E7F',
    'ml-data-science-review':        '#D24F71',
    'opaque-team':                   '#DE6065',
    'r-package-review':              '#E97158',
    'scrum-team':                    '#F1844B',
  },

  cividis: {
    'ai-self-care':                  '#4E576C',
    'devops-platform-engineering':   '#5C616E',
    'fullstack-web-dev':             '#6A6C71',
    'gxp-compliance-validation':     '#767676',
    'ml-data-science-review':        '#848179',
    'opaque-team':                   '#918C78',
    'r-package-review':              '#A09877',
    'scrum-team':                    '#B0A473',
  },

  mako: {
    'ai-self-care':                  '#751F58',
    'devops-platform-engineering':   '#8E1D5B',
    'fullstack-web-dev':             '#A7185A',
    'gxp-compliance-validation':     '#C01654',
    'ml-data-science-review':        '#D5224A',
    'opaque-team':                   '#E43841',
    'r-package-review':              '#EE543F',
    'scrum-team':                    '#F2704D',
  },

  rocket: {
    'ai-self-care':                  '#414081',
    'devops-platform-engineering':   '#3E5095',
    'fullstack-web-dev':             '#38629D',
    'gxp-compliance-validation':     '#3572A1',
    'ml-data-science-review':        '#3483A5',
    'opaque-team':                   '#3492A8',
    'r-package-review':              '#36A3AB',
    'scrum-team':                    '#3DB4AD',
  },

  turbo: {
    'ai-self-care':                  '#18D6CB',
    'devops-platform-engineering':   '#25ECA7',
    'fullstack-web-dev':             '#54FA77',
    'gxp-compliance-validation':     '#8CFF4A',
    'ml-data-science-review':        '#B6F735',
    'opaque-team':                   '#DAE336',
    'r-package-review':              '#F4C73A',
    'scrum-team':                    '#FEA632',
  },
};

export function getTeamColor(teamId) {
  if (teamId && TEAM_PALETTE_COLORS[currentTheme]?.[teamId]) {
    return TEAM_PALETTE_COLORS[currentTheme][teamId];
  }
  const colors = TEAM_PALETTE_COLORS[currentTheme];
  if (colors) {
    const vals = Object.values(colors);
    return vals[0] || '#00ffcc';
  }
  return '#00ffcc';
}

export const TEAM_CONFIG = {
  radius: 7,
  glowRadius: 20,
  glowOpacity: 0.55,
};

// ── Complexity configs (unchanged) ──────────────────────────────────
export const COMPLEXITY_CONFIG = {
  basic:        { radius: 5, glowRadius: 14, glowOpacity: 0.4,  label: 'Basic' },
  intermediate: { radius: 5, glowRadius: 18, glowOpacity: 0.5,  label: 'Intermediate' },
  advanced:     { radius: 5, glowRadius: 22, glowOpacity: 0.6,  label: 'Advanced' },
};

export const COMPLEXITY_BADGE_COLORS = {
  basic:        '#00ff88',
  intermediate: '#ffdd00',
  advanced:     '#dd44ff',
};

// ── Featured hub nodes (viz-layer config, not skill metadata) ────────
export const FEATURED_NODES = {
  'skill-creation':      { radius: 9, tier: 'primary' },
  'skill-evolution':     { radius: 7, tier: 'secondary' },
  'create-skill-glyph':  { radius: 7, tier: 'secondary' },
};

const _rgbaCache = new Map();
export function hexToRgba(hex, alpha) {
  const key = hex + '|' + alpha;
  let val = _rgbaCache.get(key);
  if (val !== undefined) return val;
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  val = `rgba(${r},${g},${b},${alpha})`;
  _rgbaCache.set(key, val);
  return val;
}
