#!/usr/bin/env Rscript
# build-workflow.R - Generate workflow diagram from PUT annotations via putior
#
# Scans viz/ source files for putior annotations and generates a Mermaid
# flowchart at public/data/workflow.mmd. Replaces the hardcoded Mermaid
# template that previously lived in build-workflow.js.
#
# Usage: Rscript build-workflow.R
#
# put id:"generate_diagram", label:"Generate Mermaid workflow from PUT annotations", node_type:"process"

# ── Setup ────────────────────────────────────────────────────────────────
script_dir <- if (nzchar(Sys.getenv("RSCRIPT_DIR"))) {
  Sys.getenv("RSCRIPT_DIR")
} else {
  tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) ".")
}

output_path <- file.path(script_dir, "public", "data", "workflow.mmd")

# ── Check putior is available ────────────────────────────────────────────
if (!requireNamespace("putior", quietly = TRUE)) {
  stop(
    "putior package is required but not installed.\n",
    "Install with: renv::install('pjt222/putior')",
    call. = FALSE
  )
}

# ── Scan for PUT annotations ────────────────────────────────────────────
message("Scanning viz/ for PUT annotations...")
workflow <- putior::put(
  script_dir,
  pattern = "\\.(js|R)$",
  recursive = TRUE,
  include_line_numbers = TRUE,
  validate = TRUE,
  exclude = c("build-workflow\\.js$", "build-workflow\\.R$")
)

if (is.null(workflow) || nrow(workflow) == 0) {
  stop("No PUT annotations found in viz/", call. = FALSE)
}

message(sprintf("  Found %d annotations across %d files",
                nrow(workflow), length(unique(workflow$file_name))))

# ── Generate Mermaid diagram via putior with cyberpunk palette ──────────
cyberpunk <- putior::put_theme(
  base     = "dark",
  input    = c(fill = "#1a1a2e", stroke = "#00ff88", color = "#00ff88"),
  process  = c(fill = "#16213e", stroke = "#44ddff", color = "#44ddff"),
  output   = c(fill = "#0f3460", stroke = "#ff3366", color = "#ff3366"),
  decision = c(fill = "#1a1a2e", stroke = "#ffaa33", color = "#ffaa33"),
  artifact = c(fill = "#0a0a1a", stroke = "#888888", color = "#aaaaaa"),
  start    = c(fill = "#1a1a2e", stroke = "#00ff88", color = "#00ff88"),
  end      = c(fill = "#0f3460", stroke = "#ff3366", color = "#ff3366")
)

mermaid_raw <- putior::put_diagram(
  workflow,
  output = "raw",
  direction = "TD",
  palette = cyberpunk,
  show_source_info = TRUE,
  source_info_style = "subgraph",
  show_artifacts = FALSE,
  show_workflow_boundaries = TRUE,
  node_labels = "label"
)

# Assemble final diagram with header comment
mermaid_final <- paste0(
  "%% Auto-generated by build-workflow.R (putior) \u2014 do not edit manually\n",
  "%% Source: PUT annotations across viz/ codebase\n",
  mermaid_raw, "\n"
)

# ── Write output ─────────────────────────────────────────────────────────
dir.create(dirname(output_path), recursive = TRUE, showWarnings = FALSE)
writeLines(mermaid_final, output_path)

message(sprintf("Generated %s", output_path))
message(sprintf("  Nodes: %d  |  Files: %d",
                nrow(workflow), length(unique(workflow$file_name))))
